Allows filter by artist
wrobin/favesound-redux pull request #116
Opened 2018-02-17 11:33 UTC by gokulchandra

Fixes #83  , Enabling users to filter tracks by artist name.

2018-02-17 11:45 UTC, rwieruch commented
That's awesome! @MiniPekka do you have time to check this PR? :)

2018-02-19 02:48 UTC, MiniPekka commented
Yeah I'm on it. Sorry I was a little bit busy recently.

2018-02-19 04:21 UTC, chriszhangusc requested changes
Looks good and works. Just change the "" to ''.

2018-02-19 04:21 UTC, chriszhangusc commented on src/components/StreamActivities/index.js
> +import { getArtistFilter } from "../../constants/artistFilter";
'' instead of "" for consistency.

2018-02-19 10:23 UTC, gokulchandra commented on src/components/StreamActivities/index.js
> +import { getArtistFilter } from "../../constants/artistFilter";
Done in latest commit.

2018-02-19 18:23 UTC, chriszhangusc approved these changes

2018-02-19 19:12 UTC, merged